services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_NAME}
    ports:
      - "${APP_DB_PORT}:5432"
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      APP_DB_NAME: ${APP_DB_NAME}
      APP_DB_HOST: db
      APP_DB_PORT: ${APP_DB_PORT}
    ports:
      - "${APP_API_PORT}:3000"
    depends_on:
      - db

 